# Generated by Django 4.2.15 on 2024-08-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_registor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_registor',
            new_name='Member',
        ),
    ]
